heat_template_version: 2018-03-02

# Déclaration des paramètres
parameters:

# ---------------- EXERCICE 1: NETWORKS & SUBNETS ---------------

  cidr_ip_admin: 
    description: Plage d'adresse IP autorisées pour le réseau d'admin
    type: string
    default: 10.0.0.0/24
  administration_network:
    description : Réseau accessible de l'extérieur. 
    type: string
    default: public
  dns_nameservers_ip_1:
    description : IP du serveur DNS principal (serveur public). 
    type: string
    default: 8.8.8.8
  dns_nameservers_ip_2: 
    description: IP du serveur DNS secondaire (serveur public). 
    type: string
    default: 1.1.1.1
  allocation_pool_start:
    description: Début de la plage d'adresse IP autorisée pour le sous-réseau
    type: string
    default: 10.0.0.2
  allocation_pool_end:
    description: Fin de la plage d'adresse IP autorisée pour le sous-réseau
    type: string
    default: 10.0.0.250



# Déclaration des ressources/objets
resources:

# ---------------- EXERCICE 1: NETWORKS & SUBNETS ---------------

# Réseau ADMIN
  network_admin:
    description: Réseau d'administration
    type: OS::Neutron::Net
    properties:
      name: string

  subnet_network_admin:
    description: Sous-réseau d'administration
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: string }
      name: subnet_network_admin
      ip_version: 4
      cidr: { get_param: string } 
      allocation_pools: [{start: {get_param: string}, end: {get_param: string }}]
      enable_dhcp: true
      dns_nameservers: [{ get_param: string }, { get_param: string }]

  router_admin_FIP_ADMIN:
    description : Routeur permettant de créer le réseau d'administration 
    type: OS::Neutron::Router
    properties:
      name: router_admin_FIP_ADMIN
      external_gateway_info: {network: { get_param: string} }

  router_admin_FIP_ADMIN_interface:
    description: Interface permettant de lier le réseau d'administration et le sous-réseau
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: string }
      subnet_id: { get_resource: string }





